registry:
  grocery_agent:
    runtime:
      type: executable
      command: ["python", "app.py"]
      working_dir: "D:/internet of agents hackathon/"
      environment:
        - name: "AIML_API_KEY"
          value: "<YOUR_KEY_HERE>"
        - name: "SERPER_API_KEY"
          value: "<YOUR_KEY_HERE>"
    meta:
      description: "Pakistan grocery comparison agent"
      author: "Aksystems"
      tags:
        - grocery
        - shopping
